-- TABELAS SEM DEPENDÊNCIAS

CREATE TABLE IF NOT EXISTS "CUSTOMER" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NAME" VARCHAR NOT NULL,
    "PHONE" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL,
    "CPF" VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS "EMPLOYEE" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NAME" VARCHAR NOT NULL,
    "CPF" VARCHAR UNIQUE,
    "ROLE" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS "SERVICES" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SERVICE" VARCHAR NOT NULL,
    "DESCRIPTION" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS "AUTHENTICATION" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "USER" VARCHAR UNIQUE,
    "PASSWORD" VARCHAR,
    "ACCESS" VARCHAR
);

-- TABELAS COM DEPENDÊNCIAS

CREATE TABLE IF NOT EXISTS "VEHICLE" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PLATE" VARCHAR NOT NULL,
    "MODEL" VARCHAR NOT NULL,
    "BRAND" VARCHAR,
    "FK_CUSTOMER" INTEGER NOT NULL,
    FOREIGN KEY ("FK_CUSTOMER") REFERENCES "CUSTOMER"("ID")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "APPOINTMENT" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "FK_VEHICLE" INTEGER NOT NULL,
    "START_DATE" DATETIME NOT NULL,
    "END_DATE" DATETIME,
    "SERVICE" INTEGER NOT NULL,
    "STATUS" VARCHAR NOT NULL,
    "PRICE" REAL,
    FOREIGN KEY ("SERVICE") REFERENCES "SERVICES"("ID")
    ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("FK_VEHICLE") REFERENCES "VEHICLE"("ID")
    ON UPDATE NO ACTION ON DELETE CASCADE
);

-- TABELA DE JUNÇÃO
CREATE TABLE IF NOT EXISTS "COMMISSIONERS" (
    "FK_APPOINTMENT" INTEGER NOT NULL,
    "FK_EMPLOYEE" INTEGER NOT NULL,
    PRIMARY KEY("FK_APPOINTMENT", "FK_EMPLOYEE"),
    FOREIGN KEY ("FK_EMPLOYEE") REFERENCES "EMPLOYEE"("ID")
    ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY ("FK_APPOINTMENT") REFERENCES "APPOINTMENT"("ID")
    ON UPDATE NO ACTION ON DELETE CASCADE
);