CREATE TABLE IF NOT EXISTS "CUSTOMER" (
	"ID" INTEGER NOT NULL UNIQUE,
	"NAME" VARCHAR NOT NULL,
	"PHONE" VARCHAR NOT NULL,
	"EMAIL" VARCHAR NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "VEHICLE" (
	"ID" INTEGER NOT NULL UNIQUE,
	"PLATE" VARCHAR NOT NULL,
	"MODEL" VARCHAR NOT NULL,
	"BRAND" VARCHAR,
	"FK_CUSTOMER" INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY ("FK_CUSTOMER") REFERENCES "CUSTOMER"("ID")
	ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "APPOINTMENT" (
	"ID" INTEGER NOT NULL UNIQUE,
	"FK_VEHICLE" INTEGER NOT NULL,
	"START_DATE" DATETIME NOT NULL,
	"END_DATE" DATETIME,
	"SERVICE" INTEGER NOT NULL,
	"STATUS" INTEGER NOT NULL,
	"PRICE" REAL,
	PRIMARY KEY("ID"),
	FOREIGN KEY ("FK_VEHICLE") REFERENCES "VEHICLE"("ID")
	ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY ("STATUS") REFERENCES "STATUS"("ID")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "EMPLOYEE" (
	"ID" INTEGER NOT NULL UNIQUE,
	"NAME" VARCHAR NOT NULL,
	"ROLE" VARCHAR NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "STATUS" (
	"ID" INTEGER NOT NULL UNIQUE,
	"NAME" VARCHAR NOT NULL,
	"DESCRIPTION" VARCHAR,
	PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS "COMMISSIONERS" (
	"FK_APPOINTMENT" INTEGER NOT NULL,
	"FK_EMPLOYEE" INTEGER NOT NULL,
	PRIMARY KEY("FK_APPOINTMENT", "FK_EMPLOYEE"),
	FOREIGN KEY ("FK_EMPLOYEE") REFERENCES "EMPLOYEE"("ID")
	ON UPDATE NO ACTION ON DELETE SET NULL,
	FOREIGN KEY ("FK_APPOINTMENT") REFERENCES "APPOINTMENT"("ID")
	ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "SERVICES" (
	"ID" INTEGER NOT NULL UNIQUE,
	"SERVICE" VARCHAR NOT NULL,
	"DESCRIPTION" VARCHAR NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY ("ID") REFERENCES "APPOINTMENT"("SERVICE")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
